### ISSUE TITLE
Does this work for https?

### ISSUE THREAD

**Issue by reergymerej** [adisreyaj/vscode-sonarqube-status#1]
I've configured the project key and url, but there's no info about auth.  I don't get any errors either, so I am not sure what it's doing.

Thanks!

**Comment by adisreyaj** [comment]
I really sorry for the very late reply...I know there is not point in even replying at the moment.
I don't know how I missed an open issue, it never came to my attention.

Currently it will support HTTP urls, I haven't tested it with HTTPS enabled server.

**Comment by adisreyaj** [comment]
It also works with https now.
