### ISSUE TITLE
Use Sonar Token instead of login/password

### ISSUE THREAD

**Issue by fredericdasilva** [adisreyaj/vscode-sonarqube-status#24]
Hello,

I would try to use this pluggin to connect to my sonar server for which I am using token. Is it possible to use token instead of login/password ?
**exemple** : 
{
  "project": "adisreyaj_compito",
  "sonarURL": "https://sonarcloud.io",
  "auth": {
    "token": "fkqsfbsdkfn6789dlqsfsldnfsd",
  }
}
Thanks
FD

**Comment by rick-cgi** [comment]
Suspect the issue is in your sonarqube-sdk repository, where it looks like the validator utils are expecting both a username and password to be not null. If either is null then an error is thrown. See https://github.com/adisreyaj/sonarqube-sdk/blob/main/src/utils/validator.util.ts

**Comment by JoeEarly** [comment]
Ran into this issue for a private org repo...any plans to update soon?

**Comment by adisreyaj** [comment]
> Suspect the issue is in your sonarqube-sdk repository, where it looks like the validator utils are expecting both a username and password to be not null. If either is null then an error is thrown. See https://github.com/adisreyaj/sonarqube-sdk/blob/main/src/utils/validator.util.ts

Looks like it. Will work this weekend to push the update.

**Comment by clown-helang** [comment]
I have the same demand and hope to support you as soon as possible
