### ISSUE TITLE
does not work for local sonar server

### ISSUE THREAD

**Issue by gautam-shipt** [adisreyaj/vscode-sonarqube-status#6]
I have a local sonar cube server running on a docker image . the address is http://localhost:9000 
When I provide this information it fails I verified the scan works with same address and key I testing using the command line scanner . 
I tried removing the port from the address it does not give error but do not perform the scan.

**Comment by adisreyaj** [comment]
Issue has been addressed in this commit 33a09446ecd5f4aa911eabe8a5d8e17a3c5e4687

New version (v0.2.0)  has been pushed to Marketplace.
